# https://github.com/golang/go/issues/59968
name: ʕ◔ϖ◔ʔ

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci-go.yml'
      - '**.go'
      - 'go.*'
  pull_request:
    paths:
      - '.github/workflows/ci-go.yml'
      - '**.go'
      - 'go.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - run: go build -v -race ./...
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - run: go test ./...
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - run: go vet ./...
      - name: check format
        run: go fmt ./... && git add --intent-to-add . && git diff --exit-code
