name: 📸

on:
  schedule:
    # Every 10:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 1 * * *'
  workflow_dispatch:

jobs:
  bump_snapshot:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: '3.42.42' # selfup { "regex": "\\d\\.\\d+\\.\\d+", "script": "task --version | cut -d ' ' -f 3" }
      - run: |
          task snapshot | tee -a snapshot.txt
